<?php

namespace Database\Seeders;

use App\Models\Room;
use Illuminate\Database\Seeder;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Seeds 44 rooms across all 5 Soleil locations. Requires LocationSeeder to run first.
     * Uses updateOrCreate so re-running is safe (no duplicates).
     *
     * Location breakdown:
     *   Location 1 — Soleil Hostel            :  9 rooms (101–109)
     *   Location 2 — Soleil House             : 10 rooms (201–210)
     *   Location 3 — Soleil Urban Villa       :  7 rooms (301–307)
     *   Location 4 — Soleil Boutique Homestay : 11 rooms (401–411)
     *   Location 5 — Soleil Riverside Villa   :  7 rooms (501–507)
     */
    public function run(): void
    {
        $rooms = [
            // ── Location 1: Soleil Hostel (9 phòng) ─────────────────────────
            [
                'name' => 'Phòng Tiêu Chuẩn',
                'description' => 'Phòng tiêu chuẩn thoải mái, phù hợp cho khách du lịch solo hoặc cặp đôi.',
                'image_url' => 'https://images.unsplash.com/photo-1631049552057-403cdb8f0658?w=800&q=80&fit=crop',
                'price' => 420000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 1,
                'room_number' => '101',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Ký Túc Xá',
                'description' => 'Phòng dorm giá rẻ với giường tầng, lý tưởng cho khách ba lô.',
                'image_url' => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80&fit=crop',
                'price' => 350000,
                'max_guests' => 6,
                'status' => 'available',
                'location_id' => 1,
                'room_number' => '102',
                'room_type_code' => 'dorm',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Cao Cấp',
                'description' => 'Phòng cao cấp rộng rãi với tầm nhìn thành phố, tiện nghi hiện đại.',
                'image_url' => 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80&fit=crop',
                'price' => 550000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 1,
                'room_number' => '103',
                'room_type_code' => 'deluxe',
                'room_tier' => 2,
            ],
            [
                'name' => 'Phòng Riêng Tư',
                'description' => 'Phòng riêng tư yên tĩnh, phù hợp cho cặp đôi hoặc gia đình nhỏ.',
                'image_url' => 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80&fit=crop',
                'price' => 500000,
                'max_guests' => 3,
                'status' => 'available',
                'location_id' => 1,
                'room_number' => '104',
                'room_type_code' => 'private',
                'room_tier' => 2,
            ],
            [
                'name' => 'Villa Sân Vườn',
                'description' => 'Villa có sân vườn riêng, không gian nghỉ dưỡng sang trọng giữa thiên nhiên.',
                'image_url' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&fit=crop',
                'price' => 650000,
                'max_guests' => 4,
                'status' => 'available',
                'location_id' => 1,
                'room_number' => '105',
                'room_type_code' => 'villa',
                'room_tier' => 3,
            ],
            [
                'name' => 'Phòng Tiêu Chuẩn Plus',
                'description' => 'Phòng tiêu chuẩn nâng cấp với bồn tắm và minibar, hướng sân trong.',
                'image_url' => 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80&fit=crop',
                'price' => 440000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 1,
                'room_number' => '106',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Ký Túc Xá Nữ',
                'description' => 'Phòng dorm chỉ dành cho nữ, an toàn và thoải mái với khoá tủ riêng.',
                'image_url' => 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80&fit=crop',
                'price' => 350000,
                'max_guests' => 8,
                'status' => 'available',
                'location_id' => 1,
                'room_number' => '107',
                'room_type_code' => 'dorm',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Deluxe Tầng Cao',
                'description' => 'Phòng deluxe tầng 3, cửa sổ lớn nhìn ra phố Tố Hữu, nội thất mới.',
                'image_url' => 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80&fit=crop',
                'price' => 570000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 1,
                'room_number' => '108',
                'room_type_code' => 'deluxe',
                'room_tier' => 2,
            ],
            [
                'name' => 'Villa Gia Đình',
                'description' => 'Villa 2 tầng dành cho gia đình, 3 phòng ngủ, bếp riêng và sân BBQ.',
                'image_url' => 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80&fit=crop',
                'price' => 750000,
                'max_guests' => 6,
                'status' => 'available',
                'location_id' => 1,
                'room_number' => '109',
                'room_type_code' => 'villa',
                'room_tier' => 4,
            ],

            // ── Location 2: Soleil House (12 phòng) ─────────────────────────
            [
                'name' => 'Phòng Tiêu Chuẩn',
                'description' => 'Phòng tiêu chuẩn sạch sẽ, đầy đủ tiện nghi cơ bản cho khách lưu trú ngắn ngày.',
                'image_url' => 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80&fit=crop',
                'price' => 420000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 2,
                'room_number' => '201',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Ký Túc Xá',
                'description' => 'Phòng dorm thoáng mát với đầy đủ ổ cắm điện và tủ khoá cá nhân.',
                'image_url' => 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80&fit=crop',
                'price' => 350000,
                'max_guests' => 8,
                'status' => 'available',
                'location_id' => 2,
                'room_number' => '202',
                'room_type_code' => 'dorm',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Cao Cấp Hướng Biển',
                'description' => 'Phòng cao cấp view biển, ban công riêng, đồ nội thất cao cấp.',
                'image_url' => 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80&fit=crop',
                'price' => 550000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 2,
                'room_number' => '203',
                'room_type_code' => 'deluxe',
                'room_tier' => 2,
            ],
            [
                'name' => 'Villa Hồ Bơi',
                'description' => 'Villa sang trọng với hồ bơi riêng, không gian mở hoàn toàn, tầm nhìn panorama.',
                'image_url' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80&fit=crop',
                'price' => 750000,
                'max_guests' => 5,
                'status' => 'available',
                'location_id' => 2,
                'room_number' => '204',
                'room_type_code' => 'villa',
                'room_tier' => 4,
            ],
            [
                'name' => 'Phòng Tiêu Chuẩn Garden View',
                'description' => 'Phòng tiêu chuẩn nhìn ra khu vườn xanh, yên tĩnh và trong lành.',
                'image_url' => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80&fit=crop',
                'price' => 430000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 2,
                'room_number' => '205',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Riêng Tư',
                'description' => 'Phòng riêng tư với giường queen-size, phòng tắm riêng, ấm cúng.',
                'image_url' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80&fit=crop',
                'price' => 490000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 2,
                'room_number' => '206',
                'room_type_code' => 'private',
                'room_tier' => 2,
            ],
            [
                'name' => 'Phòng Deluxe Ban Công',
                'description' => 'Phòng deluxe có ban công riêng, đầy đủ tiện nghi cao cấp, view sân vườn.',
                'image_url' => 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80&fit=crop',
                'price' => 560000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 2,
                'room_number' => '207',
                'room_type_code' => 'deluxe',
                'room_tier' => 2,
            ],
            [
                'name' => 'Phòng Ký Túc Xá Mix',
                'description' => 'Phòng dorm hỗn hợp 10 giường, tủ khoá và ổ cắm riêng mỗi giường.',
                'image_url' => 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80&fit=crop',
                'price' => 360000,
                'max_guests' => 10,
                'status' => 'available',
                'location_id' => 2,
                'room_number' => '208',
                'room_type_code' => 'dorm',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Tiêu Chuẩn Twin',
                'description' => 'Phòng tiêu chuẩn 2 giường đơn, phù hợp cho 2 bạn bè du lịch.',
                'image_url' => 'https://images.unsplash.com/photo-1631049552057-403cdb8f0658?w=800&q=80&fit=crop',
                'price' => 440000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 2,
                'room_number' => '209',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Riêng Tư Deluxe',
                'description' => 'Phòng riêng tư deluxe rộng 35m², bồn tắm đứng, minibar, view sân vườn.',
                'image_url' => 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&q=80&fit=crop',
                'price' => 520000,
                'max_guests' => 3,
                'status' => 'available',
                'location_id' => 2,
                'room_number' => '210',
                'room_type_code' => 'private',
                'room_tier' => 2,
            ],

            // ── Location 3: Soleil Urban Villa (7 phòng) ────────────────────
            [
                'name' => 'Phòng Tiêu Chuẩn',
                'description' => 'Phòng tiêu chuẩn hiện đại trong khu đô thị mới, đầy đủ tiện nghi.',
                'image_url' => 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80&fit=crop',
                'price' => 420000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 3,
                'room_number' => '301',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Ký Túc Xá',
                'description' => 'Phòng dorm giá rẻ với không gian sống chung hiện đại, view thành phố.',
                'image_url' => 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80&fit=crop',
                'price' => 350000,
                'max_guests' => 6,
                'status' => 'available',
                'location_id' => 3,
                'room_number' => '302',
                'room_type_code' => 'dorm',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Cao Cấp View Phố',
                'description' => 'Phòng cao cấp nhìn ra khu đô thị BGI Topaz, nội thất sang trọng.',
                'image_url' => 'https://images.unsplash.com/photo-1587985064135-0366536eab42?w=800&q=80&fit=crop',
                'price' => 550000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 3,
                'room_number' => '303',
                'room_type_code' => 'deluxe',
                'room_tier' => 2,
            ],
            [
                'name' => 'Villa Hồ Bơi Vô Cực',
                'description' => 'Villa với hồ bơi vô cực tầng thượng, gym riêng, tầm nhìn toàn cảnh.',
                'image_url' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80&fit=crop',
                'price' => 800000,
                'max_guests' => 4,
                'status' => 'available',
                'location_id' => 3,
                'room_number' => '304',
                'room_type_code' => 'villa',
                'room_tier' => 4,
            ],
            [
                'name' => 'Phòng Tiêu Chuẩn City View',
                'description' => 'Phòng tiêu chuẩn tầng trung, nhìn ra khu dân cư mới, gần trung tâm thương mại.',
                'image_url' => 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80&fit=crop',
                'price' => 440000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 3,
                'room_number' => '305',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Riêng Tư Urban',
                'description' => 'Phòng riêng tư phong cách đô thị hiện đại, trang bị smart TV và bồn tắm.',
                'image_url' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80&fit=crop',
                'price' => 510000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 3,
                'room_number' => '306',
                'room_type_code' => 'private',
                'room_tier' => 2,
            ],
            [
                'name' => 'Villa Penthouse',
                'description' => 'Penthouse tầng thượng toàn khu, sân thượng riêng, bếp đầy đủ, tầm nhìn 360°.',
                'image_url' => 'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=800&q=80&fit=crop',
                'price' => 950000,
                'max_guests' => 6,
                'status' => 'available',
                'location_id' => 3,
                'room_number' => '307',
                'room_type_code' => 'villa',
                'room_tier' => 4,
            ],

            // ── Location 4: Soleil Boutique Homestay (11 phòng) ─────────────
            [
                'name' => 'Phòng Boutique Đơn',
                'description' => 'Phòng đơn phong cách boutique, trang trí tinh tế mang đậm văn hoá Huế.',
                'image_url' => 'https://images.unsplash.com/photo-1564078516393-cf04bd966897?w=800&q=80&fit=crop',
                'price' => 420000,
                'max_guests' => 1,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '401',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Boutique Đôi',
                'description' => 'Phòng đôi ấm cúng với giường king-size, sân vườn nhỏ riêng tư.',
                'image_url' => 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80&fit=crop',
                'price' => 500000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '402',
                'room_type_code' => 'private',
                'room_tier' => 2,
            ],
            [
                'name' => 'Phòng Gia Đình',
                'description' => 'Phòng gia đình rộng rãi, 2 phòng ngủ liên thông, có bếp nhỏ và BBQ.',
                'image_url' => 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80&fit=crop',
                'price' => 650000,
                'max_guests' => 5,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '403',
                'room_type_code' => 'villa',
                'room_tier' => 3,
            ],
            [
                'name' => 'Phòng Cao Cấp Vườn',
                'description' => 'Phòng cao cấp nhìn ra khu vườn xanh mát, thiết kế kết hợp cổ điển và hiện đại.',
                'image_url' => 'https://images.unsplash.com/photo-1609942072337-c3370e820005?w=800&q=80&fit=crop',
                'price' => 580000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '404',
                'room_type_code' => 'deluxe',
                'room_tier' => 2,
            ],
            [
                'name' => 'Phòng Tiêu Chuẩn Heritage',
                'description' => 'Phòng tiêu chuẩn décor phong cách nhà cổ Huế, nội thất gỗ tự nhiên.',
                'image_url' => 'https://images.unsplash.com/photo-1566195992011-5f6b21e539aa?w=800&q=80&fit=crop',
                'price' => 430000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '405',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Ký Túc Xá Boutique',
                'description' => 'Phòng dorm 6 giường thiết kế boutique, tủ khoá gỗ và đèn đọc sách riêng.',
                'image_url' => 'https://images.unsplash.com/photo-1631049421450-348ccd7f8949?w=800&q=80&fit=crop',
                'price' => 360000,
                'max_guests' => 6,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '406',
                'room_type_code' => 'dorm',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Deluxe Cổ Điển',
                'description' => 'Phòng deluxe phong cách hoàng triều, tranh thêu, cửa sổ hoa văn gỗ.',
                'image_url' => 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=800&q=80&fit=crop',
                'price' => 590000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '407',
                'room_type_code' => 'deluxe',
                'room_tier' => 2,
            ],
            [
                'name' => 'Phòng Riêng Tư Vườn',
                'description' => 'Phòng riêng tư có cửa thông ra vườn riêng, võng và bộ bàn trà ngoài trời.',
                'image_url' => 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=800&q=80&fit=crop',
                'price' => 510000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '408',
                'room_type_code' => 'private',
                'room_tier' => 2,
            ],
            [
                'name' => 'Phòng Tiêu Chuẩn Twin Heritage',
                'description' => 'Phòng 2 giường đơn décor nhà cổ, thích hợp 2 bạn bè hoặc 2 trẻ em.',
                'image_url' => 'https://images.unsplash.com/photo-1631049552240-59c37f38802b?w=800&q=80&fit=crop',
                'price' => 440000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '409',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Villa Sân Vườn Boutique',
                'description' => 'Villa nhỏ độc lập trong khuôn viên, sân riêng, bể cá koi và khóm trúc.',
                'image_url' => 'https://images.unsplash.com/photo-1615460549969-36fa19521a4f?w=800&q=80&fit=crop',
                'price' => 700000,
                'max_guests' => 4,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '410',
                'room_type_code' => 'villa',
                'room_tier' => 3,
            ],
            [
                'name' => 'Phòng Deluxe Lầu',
                'description' => 'Phòng deluxe tầng 2, ban công nhìn ra đường Lê Duẩn và mái ngói cổ.',
                'image_url' => 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80&fit=crop',
                'price' => 600000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 4,
                'room_number' => '411',
                'room_type_code' => 'deluxe',
                'room_tier' => 2,
            ],

            // ── Location 5: Soleil Riverside Villa (6 phòng) ────────────────
            [
                'name' => 'Phòng Hướng Sông',
                'description' => 'Phòng tiêu chuẩn với ban công nhìn ra sông Bồ, không khí trong lành.',
                'image_url' => 'https://images.unsplash.com/photo-1499678329028-101435549a4e?w=800&q=80&fit=crop',
                'price' => 450000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 5,
                'room_number' => '501',
                'room_type_code' => 'standard',
                'room_tier' => 1,
            ],
            [
                'name' => 'Phòng Dorm Bên Sông',
                'description' => 'Phòng dorm thoáng đãng, cách bờ sông 50m, lý tưởng cho nhóm bạn.',
                'image_url' => 'https://images.unsplash.com/photo-1564078516393-cf04bd966897?w=800&q=80&fit=crop',
                'price' => 360000,
                'max_guests' => 8,
                'status' => 'available',
                'location_id' => 5,
                'room_number' => '502',
                'room_type_code' => 'dorm',
                'room_tier' => 1,
            ],
            [
                'name' => 'Villa Riverside',
                'description' => 'Villa riêng sát sông, có bãi kayak và cần câu riêng, bể bơi ngoài trời.',
                'image_url' => 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800&q=80&fit=crop',
                'price' => 900000,
                'max_guests' => 6,
                'status' => 'available',
                'location_id' => 5,
                'room_number' => '503',
                'room_type_code' => 'villa',
                'room_tier' => 4,
            ],
            [
                'name' => 'Phòng Deluxe Panorama',
                'description' => 'Phòng deluxe tầng cao, tầm nhìn panorama dòng sông và đồng lúa xanh.',
                'image_url' => 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80&fit=crop',
                'price' => 600000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 5,
                'room_number' => '504',
                'room_type_code' => 'deluxe',
                'room_tier' => 2,
            ],
            [
                'name' => 'Phòng Riêng Tư Riverside',
                'description' => 'Phòng riêng tư yên tĩnh, bồn tắm ngoài trời nhìn ra sông, nội thất gỗ.',
                'image_url' => 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80&fit=crop',
                'price' => 520000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 5,
                'room_number' => '505',
                'room_type_code' => 'private',
                'room_tier' => 2,
            ],
            [
                'name' => 'Villa Gia Đình Sông Nước',
                'description' => 'Villa 3 phòng ngủ cho gia đình lớn, bến thuyền riêng, BBQ và bếp ngoài trời.',
                'image_url' => 'https://images.unsplash.com/photo-1499678329028-101435549a4e?w=800&q=80&fit=crop',
                'price' => 950000,
                'max_guests' => 8,
                'status' => 'available',
                'location_id' => 5,
                'room_number' => '506',
                'room_type_code' => 'villa',
                'room_tier' => 4,
            ],
            [
                'name' => 'Phòng Deluxe River Garden',
                'description' => 'Phòng deluxe nhìn ra vườn ven sông, cửa kính lớn, ghế đọc sách bên bệ cửa sổ.',
                'image_url' => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80&fit=crop',
                'price' => 620000,
                'max_guests' => 2,
                'status' => 'available',
                'location_id' => 5,
                'room_number' => '507',
                'room_type_code' => 'deluxe',
                'room_tier' => 2,
            ],
        ];

        foreach ($rooms as $room) {
            Room::updateOrCreate(
                ['room_number' => $room['room_number'], 'location_id' => $room['location_id']],
                $room
            );
        }
    }
}
